<?php
/**
 * @file
 * Code for the VCR Homepage Widget feature.
 */

include_once 'vcr_homepage_widget.features.inc';

/**
 * Implements hook_theme_registry_alter().
 *
 * Let Drupal know that we've got bean--cu-homepage-widget.tpl.php in our module directory.
 */
function vcr_homepage_widget_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'vcr_homepage_widget');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'bean', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('bean');
  foreach ($hooks as $h) {
	  if (isset($theme_registry[$h]['theme paths'])) {
	    $first_element = array_shift($theme_registry[$h]['theme paths']);
	    array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
  	}
  }
}

function vcr_homepage_widget_page_alter(&$page) {
  drupal_add_js(drupal_get_path('module', 'vcr_homepage_widget') . '/js/jquery.iframe-auto-height.js');
}