<?php
/**
 * @file
 * Code for the VCR Policies feature.
 */

include_once 'vcr_policies.features.inc';

/**
 * Implements hook_theme_registry_alter().
 *
 * Let Drupal know that we've got bean--cu-slider.tpl.php in our module directory.
 */
function vcr_policies_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'vcr_policies');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'bean', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('bean');
  foreach ($hooks as $h) {
    if (isset($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
    }
  }
}

/**
 * Implements hook_node_view().
 *
 * On policy nodes, if a link or file is uploaded, send the user there.
 */
function vcr_policies_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'policy') {
    $redirect = FALSE;
    if (!empty($node->field_policy_file[LANGUAGE_NONE][0]['uri'])) {
      $redirect = file_create_url($node->field_policy_file[LANGUAGE_NONE][0]['uri']);
    }
    elseif (!empty($node->field_policy_url[LANGUAGE_NONE][0]['url'])) {
      $redirect = $node->field_policy_url[LANGUAGE_NONE][0]['url'];
    }
    if ($redirect) {
      // If the user can edit the node, show the node with a message.
      // Otherwise, redirect the user.
      if (node_access('update', $node)) {
        drupal_set_message(t('Non-priviledged users will be directed to the following url: !link', array('!link' => l($redirect, $redirect))));
      }
      else {
        drupal_goto($redirect);
      }
    }
  }
}
